/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiScreensRouteImport } from './routes/api/screens'
import { Route as ApiPlaylistsRouteImport } from './routes/api/playlists'
import { Route as ApiScreensIdRouteImport } from './routes/api/screens/$id'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'

const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreensRoute = ApiScreensRouteImport.update({
  id: '/api/screens',
  path: '/api/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPlaylistsRoute = ApiPlaylistsRouteImport.update({
  id: '/api/playlists',
  path: '/api/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScreensIdRoute = ApiScreensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiScreensRoute,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/screens': typeof ScreensRoute
  '/api/playlists': typeof ApiPlaylistsRoute
  '/api/screens': typeof ApiScreensRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/screens/$id': typeof ApiScreensIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/screens': typeof ScreensRoute
  '/api/playlists': typeof ApiPlaylistsRoute
  '/api/screens': typeof ApiScreensRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/screens/$id': typeof ApiScreensIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/playlists': typeof PlaylistsRoute
  '/screens': typeof ScreensRoute
  '/api/playlists': typeof ApiPlaylistsRoute
  '/api/screens': typeof ApiScreensRouteWithChildren
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/screens/$id': typeof ApiScreensIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/playlists'
    | '/screens'
    | '/api/playlists'
    | '/api/screens'
    | '/api/auth/login'
    | '/api/screens/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/playlists'
    | '/screens'
    | '/api/playlists'
    | '/api/screens'
    | '/api/auth/login'
    | '/api/screens/$id'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/playlists'
    | '/screens'
    | '/api/playlists'
    | '/api/screens'
    | '/api/auth/login'
    | '/api/screens/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  PlaylistsRoute: typeof PlaylistsRoute
  ScreensRoute: typeof ScreensRoute
  ApiPlaylistsRoute: typeof ApiPlaylistsRoute
  ApiScreensRoute: typeof ApiScreensRouteWithChildren
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screens': {
      id: '/api/screens'
      path: '/api/screens'
      fullPath: '/api/screens'
      preLoaderRoute: typeof ApiScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/playlists': {
      id: '/api/playlists'
      path: '/api/playlists'
      fullPath: '/api/playlists'
      preLoaderRoute: typeof ApiPlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/screens/$id': {
      id: '/api/screens/$id'
      path: '/$id'
      fullPath: '/api/screens/$id'
      preLoaderRoute: typeof ApiScreensIdRouteImport
      parentRoute: typeof ApiScreensRoute
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiScreensRouteChildren {
  ApiScreensIdRoute: typeof ApiScreensIdRoute
}

const ApiScreensRouteChildren: ApiScreensRouteChildren = {
  ApiScreensIdRoute: ApiScreensIdRoute,
}

const ApiScreensRouteWithChildren = ApiScreensRoute._addFileChildren(
  ApiScreensRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  PlaylistsRoute: PlaylistsRoute,
  ScreensRoute: ScreensRoute,
  ApiPlaylistsRoute: ApiPlaylistsRoute,
  ApiScreensRoute: ApiScreensRouteWithChildren,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
